apiVersion: v1
kind: Secret
metadata:
  name: order-mongo-pass
type: Opaque
data:
  {{- if .Values.passwords.orderMongodb }}
  password: {{ default "" .Values.passwords.orderMongodb | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
