apiVersion: v1
kind: Secret
metadata:
  name: users-mongo-pass
type: Opaque
data:
  {{- if .Values.passwords.usersMongodb }}
  password: {{ default "" .Values.passwords.usersMongodb | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
