apiVersion: v1
kind: Service
metadata:
  name: users-mongo
  labels:
    app: acmefit
    service: users-db
spec:
  ports:
    - port: 27017
      name: mongo-users
      protocol: TCP
  selector:
    app: acmefit
    service: users-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-mongo
  labels:
    app: acmefit
    service: users-db
spec:
  selector:
    matchLabels:
      app: acmefit  # has to match .spec.template.metadata.labels
      service: users-db
  replicas: 1
  template:
    metadata:
      labels:
        app: acmefit  # has to match .spec.selector.matchLabels
        service: users-db
    spec:
      containers:
        - name: users-mongo
          image: bitnami/mongodb:4.0.8
          resources:
            {}
          ports:
            - name: users-mongo
              containerPort: 27017
              protocol: "TCP"
          env:
          - name: MONGODB_USERNAME
            value: 'root'
          - name: MONGODB_DATABASE
            value: 'acmefit'
          - name: MONGODB_ENABLE_IPV6
            value: 'no'
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: users-mongo-pass
                key: password
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: users-mongo-pass
                key: password
          volumeMounts:
            - mountPath: /bitnami
              name: mongodata
            - mountPath: /docker-entrypoint-initdb.d
              name: mongo-initdb
      volumes:
        - name: mongodata
          emptyDir: {}
        - name: mongo-initdb
          configMap:
            name: users-initdb-config
#        - name: mongodata
#          persistentVolumeClaim:
#            claimName: mongodata
